# ASP.NET Core

trigger:
- main

pool: jvPoolAgent1

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)' 
